// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQV5GXTTdQ5FTD9oroel1KE10RAq5IqKU',
    appId: '1:758942709283:web:591786fb99d31029516396',
    messagingSenderId: '758942709283',
    projectId: 'fir-series-cb7fd',
    authDomain: 'fir-series-cb7fd.firebaseapp.com',
    storageBucket: 'fir-series-cb7fd.appspot.com',
    measurementId: 'G-TL50R76P0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_-V4WCfSvK54lHbw8CoJ2nbXLLCYiZNM',
    appId: '1:758942709283:android:2d12f129ec18a3ac516396',
    messagingSenderId: '758942709283',
    projectId: 'fir-series-cb7fd',
    storageBucket: 'fir-series-cb7fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkwImWMv0zcOV43tCz34ddw_KFtDA2TWc',
    appId: '1:758942709283:ios:69d25a6f4a7d5db1516396',
    messagingSenderId: '758942709283',
    projectId: 'fir-series-cb7fd',
    storageBucket: 'fir-series-cb7fd.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );
}
